/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BookingUpdateManyWithoutLawyersInput } from "./BookingUpdateManyWithoutLawyersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsNumber,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { CaseModelUpdateManyWithoutLawyersInput } from "./CaseModelUpdateManyWithoutLawyersInput";
import { PaymentUpdateManyWithoutLawyersInput } from "./PaymentUpdateManyWithoutLawyersInput";
import { RatingUpdateManyWithoutLawyersInput } from "./RatingUpdateManyWithoutLawyersInput";
import { EnumLawyerSpecialties } from "./EnumLawyerSpecialties";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class LawyerUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BookingUpdateManyWithoutLawyersInput,
  })
  @ValidateNested()
  @Type(() => BookingUpdateManyWithoutLawyersInput)
  @IsOptional()
  @Field(() => BookingUpdateManyWithoutLawyersInput, {
    nullable: true,
  })
  bookings?: BookingUpdateManyWithoutLawyersInput;

  @ApiProperty({
    required: false,
    type: () => CaseModelUpdateManyWithoutLawyersInput,
  })
  @ValidateNested()
  @Type(() => CaseModelUpdateManyWithoutLawyersInput)
  @IsOptional()
  @Field(() => CaseModelUpdateManyWithoutLawyersInput, {
    nullable: true,
  })
  cases?: CaseModelUpdateManyWithoutLawyersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: () => PaymentUpdateManyWithoutLawyersInput,
  })
  @ValidateNested()
  @Type(() => PaymentUpdateManyWithoutLawyersInput)
  @IsOptional()
  @Field(() => PaymentUpdateManyWithoutLawyersInput, {
    nullable: true,
  })
  payments?: PaymentUpdateManyWithoutLawyersInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rating?: number | null;

  @ApiProperty({
    required: false,
    type: () => RatingUpdateManyWithoutLawyersInput,
  })
  @ValidateNested()
  @Type(() => RatingUpdateManyWithoutLawyersInput)
  @IsOptional()
  @Field(() => RatingUpdateManyWithoutLawyersInput, {
    nullable: true,
  })
  ratings?: RatingUpdateManyWithoutLawyersInput;

  @ApiProperty({
    required: false,
    enum: EnumLawyerSpecialties,
    isArray: true,
  })
  @IsEnum(EnumLawyerSpecialties, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumLawyerSpecialties], {
    nullable: true,
  })
  specialties?: Array<"Option1">;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { LawyerUpdateInput as LawyerUpdateInput };
