/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LawyerService } from "../lawyer.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LawyerCreateInput } from "./LawyerCreateInput";
import { Lawyer } from "./Lawyer";
import { LawyerFindManyArgs } from "./LawyerFindManyArgs";
import { LawyerWhereUniqueInput } from "./LawyerWhereUniqueInput";
import { LawyerUpdateInput } from "./LawyerUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";
import { CaseModelFindManyArgs } from "../../caseModel/base/CaseModelFindManyArgs";
import { CaseModel } from "../../caseModel/base/CaseModel";
import { CaseModelWhereUniqueInput } from "../../caseModel/base/CaseModelWhereUniqueInput";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { PaymentWhereUniqueInput } from "../../payment/base/PaymentWhereUniqueInput";
import { RatingFindManyArgs } from "../../rating/base/RatingFindManyArgs";
import { Rating } from "../../rating/base/Rating";
import { RatingWhereUniqueInput } from "../../rating/base/RatingWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LawyerControllerBase {
  constructor(
    protected readonly service: LawyerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Lawyer })
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: LawyerCreateInput,
  })
  async createLawyer(@common.Body() data: LawyerCreateInput): Promise<Lawyer> {
    return await this.service.createLawyer({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        location: true,
        rating: true,
        specialties: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Lawyer] })
  @ApiNestedQuery(LawyerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async lawyers(@common.Req() request: Request): Promise<Lawyer[]> {
    const args = plainToClass(LawyerFindManyArgs, request.query);
    return this.service.lawyers({
      ...args,
      select: {
        createdAt: true,
        id: true,
        location: true,
        rating: true,
        specialties: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Lawyer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async lawyer(
    @common.Param() params: LawyerWhereUniqueInput
  ): Promise<Lawyer | null> {
    const result = await this.service.lawyer({
      where: params,
      select: {
        createdAt: true,
        id: true,
        location: true,
        rating: true,
        specialties: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Lawyer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: LawyerUpdateInput,
  })
  async updateLawyer(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() data: LawyerUpdateInput
  ): Promise<Lawyer | null> {
    try {
      return await this.service.updateLawyer({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          location: true,
          rating: true,
          specialties: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Lawyer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLawyer(
    @common.Param() params: LawyerWhereUniqueInput
  ): Promise<Lawyer | null> {
    try {
      return await this.service.deleteLawyer({
        where: params,
        select: {
          createdAt: true,
          id: true,
          location: true,
          rating: true,
          specialties: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Booking",
    action: "read",
    possession: "any",
  })
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: LawyerWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        lawyer: {
          select: {
            id: true,
          },
        },

        scheduledAt: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  async connectBookings(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateLawyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  async updateBookings(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateLawyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  async disconnectBookings(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateLawyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/cases")
  @ApiNestedQuery(CaseModelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "read",
    possession: "any",
  })
  async findCases(
    @common.Req() request: Request,
    @common.Param() params: LawyerWhereUniqueInput
  ): Promise<CaseModel[]> {
    const query = plainToClass(CaseModelFindManyArgs, request.query);
    const results = await this.service.findCases(params.id, {
      ...query,
      select: {
        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,

        lawyer: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/cases")
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  async connectCases(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() body: CaseModelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cases: {
        connect: body,
      },
    };
    await this.service.updateLawyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/cases")
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  async updateCases(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() body: CaseModelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cases: {
        set: body,
      },
    };
    await this.service.updateLawyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/cases")
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  async disconnectCases(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() body: CaseModelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cases: {
        disconnect: body,
      },
    };
    await this.service.updateLawyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/payments")
  @ApiNestedQuery(PaymentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Payment",
    action: "read",
    possession: "any",
  })
  async findPayments(
    @common.Req() request: Request,
    @common.Param() params: LawyerWhereUniqueInput
  ): Promise<Payment[]> {
    const query = plainToClass(PaymentFindManyArgs, request.query);
    const results = await this.service.findPayments(params.id, {
      ...query,
      select: {
        amount: true,

        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        lawyer: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/payments")
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  async connectPayments(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        connect: body,
      },
    };
    await this.service.updateLawyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/payments")
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  async updatePayments(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        set: body,
      },
    };
    await this.service.updateLawyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/payments")
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  async disconnectPayments(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        disconnect: body,
      },
    };
    await this.service.updateLawyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/ratings")
  @ApiNestedQuery(RatingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Rating",
    action: "read",
    possession: "any",
  })
  async findRatings(
    @common.Req() request: Request,
    @common.Param() params: LawyerWhereUniqueInput
  ): Promise<Rating[]> {
    const query = plainToClass(RatingFindManyArgs, request.query);
    const results = await this.service.findRatings(params.id, {
      ...query,
      select: {
        client: {
          select: {
            id: true,
          },
        },

        comments: true,
        createdAt: true,
        id: true,

        lawyer: {
          select: {
            id: true,
          },
        },

        rating: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/ratings")
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  async connectRatings(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() body: RatingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ratings: {
        connect: body,
      },
    };
    await this.service.updateLawyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/ratings")
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  async updateRatings(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() body: RatingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ratings: {
        set: body,
      },
    };
    await this.service.updateLawyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/ratings")
  @nestAccessControl.UseRoles({
    resource: "Lawyer",
    action: "update",
    possession: "any",
  })
  async disconnectRatings(
    @common.Param() params: LawyerWhereUniqueInput,
    @common.Body() body: RatingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ratings: {
        disconnect: body,
      },
    };
    await this.service.updateLawyer({
      where: params,
      data,
      select: { id: true },
    });
  }
}
